---
- hosts: all
  roles:
    - role: '{{playbook_dir}}'
  tasks:
    - command: /usr/local/node/bin/node --version
      register: node_test_output
    - debug:
        msg: '{{ node_test_output.stdout }}'
