---
- name: checking for existing install in {{ node_install_bin_dir }}
  become: true
  stat:
    path: '{{ node_install_bin_dir }}'
  changed_when: false
  register: node_binary
- when: not node_binary.stat.exists
  block:
    - name: downloading {{ node_tgz_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ node_tgz_url }}'
        dest: '{{ node_tmp_tgz }}'
        mode: 0644
        checksum: '{{ node_checksum }}'

    - name: unarchiving into {{ node_parent_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ node_tmp_tgz }}'
        dest: '{{ node_parent_install_dir }}'
        creates: '{{ node_install_bin_dir }}'

  always:
    - name: cleanup {{ node_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ node_tmp_tgz }}'
        state: absent

- name: linking executables in {{ node_link_dir }} to {{ node_install_bin_dir }}
  become: true
  become_user: root
  with_items: '{{ node_exes }}'
  file:
    src: '{{ node_install_bin_dir }}/{{ item }}'
    dest: '{{ node_link_dir }}/{{ item }}'
    state: link
